name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build and Deploy
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          npm run deploy
        env:
          CI: false
          NODE_OPTIONS: --openssl-legacy-provider
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/willm78/mousical.git
